---
title: "Project Planner"
type: "challenge"
description: "Design a database schema with models to represent a shared project task list."
visibility: "assign"
tags: "system-check, activerecord, models, migrations"
ignore:
- "project-planner.md"
