abi = User.create(email: 'abi@aby.com', password: '1234', first_name: 'Abi', last_name: 'Abinard')
gab = User.create(email: 'gab@gab.com', password: '1234', first_name: 'Gab', last_name: 'Gabifor')
liz = User.create(email: 'liz@liz.com', password: '1234', first_name: 'Liz', last_name: 'Lizzard')
wiz = User.create(email: 'wiz@wiz.com', password: '1234', first_name: 'Wiz', last_name: 'Wizly')
gnat = User.create(email: 'gnat@gnat.com', password: '1234', first_name: 'Gnat', last_name: 'Gnater')
fup = User.create(email: 'fup@fup.com', password: '1234', first_name: 'Fup', last_name: 'Fupingsworth')
shoe = User.create(email: 'shoe@shoe.com', password: '1234', first_name: 'Shoe', last_name: 'Shoelast')
sock = User.create(email: 'sock@sock.com', password: '1234', first_name: 'Sock', last_name: 'Socker')

q = Project.create(name: 'build store', description: 'lets users shop for groceries')
r = Project.create(name: 'build house', description: 'lets users store and cook groceries')
s = Project.create(name: 'build shed', description: 'lets users store their grill')
t = Project.create(name: 'build playground', description: 'lets users\'s kids play')
u = Project.create(name: 'build slide', description: 'lets users do phsics experiments on friction')
v = Project.create(name: 'build seesaw', description: 'lets users experiment with gravity')

ProjectTeam.create(user_id: liz.id, project_id: q.id)
ProjectTeam.create(user_id: liz.id, project_id: r.id)
ProjectTeam.create(user_id: gab.id, project_id: r.id)
ProjectTeam.create(user_id: gab.id, project_id: s.id)
ProjectTeam.create(user_id: abi.id, project_id: s.id)
ProjectTeam.create(user_id: abi.id, project_id: t.id)
ProjectTeam.create(user_id: wiz.id, project_id: t.id)
ProjectTeam.create(user_id: wiz.id, project_id: u.id)
ProjectTeam.create(user_id: gnat.id, project_id: u.id)
ProjectTeam.create(user_id: gnat.id, project_id: v.id)
ProjectTeam.create(user_id: fup.id, project_id: v.id)
ProjectTeam.create(user_id: fup.id, project_id: q.id)
ProjectTeam.create(user_id: shoe.id, project_id: q.id)
ProjectTeam.create(user_id: shoe.id, project_id: r.id)
ProjectTeam.create(user_id: sock.id, project_id: r.id)
ProjectTeam.create(user_id: sock.id, project_id: s.id)
ProjectTeam.create(user_id: wiz.id, project_id: s.id)
ProjectTeam.create(user_id: wiz.id, project_id: q.id)
ProjectTeam.create(user_id: gnat.id, project_id: t.id)
ProjectTeam.create(user_id: gnat.id, project_id: q.id)
